package app

import (
	"context"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
	"github.com/user/high-school-management/backend/config"
	_ "github.com/user/high-school-management/backend/docs" // Generated by swag init
	"github.com/user/high-school-management/backend/internal/api/handler"
	"github.com/user/high-school-management/backend/internal/api/middleware"
	"github.com/user/high-school-management/backend/internal/domain"
	"github.com/user/high-school-management/backend/internal/infrastructure"
	"github.com/user/high-school-management/backend/internal/infrastructure/logger"
	"github.com/user/high-school-management/backend/internal/usecase"
	"go.uber.org/zap"
	"gorm.io/gorm"
)

type App struct {
	Config *config.Config
	DB     *gorm.DB
	Router *gin.Engine
	Server *http.Server
}

func NewApp(cfg *config.Config) *App {
	return &App{
		Config: cfg,
	}
}

func (a *App) Bootstrap() {
	logger.InitLogger()
	logger.Info("Initializing High School Management System Backend", zap.String("port", a.Config.Port))

	a.DB = infrastructure.ConnectDB(a.Config)

	// Always run GORM AutoMigrate on startup to keep schema in sync with domain models
	if err := infrastructure.RunMigrations(a.DB); err != nil {
		logger.Fatal("Database migration failed", err)
	}

	if os.Getenv("GIN_MODE") == "" {
		gin.SetMode(gin.ReleaseMode)
	}
	a.Router = gin.Default()
	a.Router.Use(middleware.ErrorRecoveryMiddleware())
	a.Router.Use(middleware.CORSMiddleware(a.DB))

	a.Router.GET("/health", func(c *gin.Context) {
		sqlDB, err := a.DB.DB()
		if err != nil {
			c.JSON(503, gin.H{"status": "down", "error": "failed to get db instance"})
			return
		}
		if err := sqlDB.Ping(); err != nil {
			c.JSON(503, gin.H{"status": "down", "error": "db ping failed"})
			return
		}
		c.JSON(200, gin.H{"status": "up"})
	})
	if os.Getenv("ENV") != "production" {
		a.Router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))
	}

	a.setupRoutes()
}

func (a *App) setupRoutes() {
	// Initialize Providers
	infra := initInfrastructure(a.Config)
	repos := initRepositories(a.DB, infra.Cache)
	usecases := initUseCases(repos, infra, a.DB, a.Config)

	// Auth Handlers (Tenant-scoped, for school frontends)
	authGroup := a.Router.Group("/api/auth")
	authGroup.Use(middleware.TenantMiddleware(a.DB))
	handler.NewAuthHandler(authGroup, repos.User, repos.Tenant, repos.Blacklist, usecases.Audit, infra.SMTP, infra.SMS, a.DB, a.Config)

	// System Auth (No tenant middleware — for the super admin portal)
	sysAuthGroup := a.Router.Group("/api/system/auth")
	handler.NewAuthHandler(sysAuthGroup, repos.User, repos.Tenant, repos.Blacklist, usecases.Audit, infra.SMTP, infra.SMS, a.DB, a.Config)

	// Webhooks (Public/Signature Verified)
	webhookGroup := a.Router.Group("/api/webhooks")
	paymentHandler := handler.NewPaymentHandler(usecases.Payment)
	webhookGroup.POST("/paystack", paymentHandler.HandleWebhook)

	// Public Routes (no auth, no tenant middleware)
	publicGroup := a.Router.Group("/api/public")
	handler.NewPublicTenantHandler(publicGroup, a.DB)

	// Static file serving for uploads (Logos, etc.)
	a.Router.Static("/uploads", "./uploads")

	// API Routes
	api := a.Router.Group("/api")

	// Global Rate Limiting (100 req/sec burst 200) - Gap #12
	globalLimiter := middleware.NewRateLimiter(100, 200).Middleware()
	api.Use(globalLimiter)

	api.Use(middleware.TenantMiddleware(a.DB))
	api.Use(middleware.AuthMiddleware(a.Config, repos.Blacklist))
	api.Use(middleware.AuditMiddleware(usecases.Audit))

	handler.NewAuditHandler(api, usecases.Audit)
	handler.NewDepartmentHandler(api, usecases.Department)
	handler.NewStudentHandler(api, usecases.Student)
	handler.NewAlumniHandler(api, usecases.Student)
	handler.NewGuardianHandler(api, usecases.Guardian, usecases.Academic)
	handler.NewHouseHandler(api, usecases.House)
	handler.NewNewsletterHandler(api, usecases.Newsletter)
	handler.NewLedgerHandler(api, usecases.Ledger)
	handler.NewCBTHandler(api, usecases.CBT)
	handler.NewReportCardHandler(api, usecases.ReportCard)
	handler.NewInventoryHandler(api, usecases.Stock)
	handler.NewProcurementHandler(api, usecases.Procurement)
	handler.NewTrackingHandler(api, usecases.Tracking)
	handler.NewTeacherHandler(api, usecases.Teacher)
	handler.NewTeacherPortalHandler(api, usecases.TeacherPortal, repos.TerminalEvaluation)
	handler.NewTeacherAssignmentHandler(api, repos.Teacher)
	handler.NewClassHandler(api, usecases.Class, repos.Class)
	handler.NewAssignmentHandler(api, usecases.Assignment)
	handler.NewGradeHandler(api, usecases.Grade)
	handler.NewAttendanceHandler(api, usecases.Attendance)
	handler.NewSubjectHandler(api, usecases.Subject)
	handler.NewTimetableHandler(api, usecases.Timetable)
	handler.NewAnalyticsHandler(api, usecases.Analytics)
	handler.NewHomeworkHandler(api, usecases.Homework)
	handler.NewInsightsHandler(api, usecases.Academic)
	handler.NewSearchHandler(api, usecases.Search)
	handler.NewIntelligenceHandler(api, usecases.Intelligence)
	handler.NewRecommendationHandler(api, usecases.Recommendation)
	handler.NewCampaignHandler(api, usecases.Campaign)
	handler.NewMessagingHandler(api, repos.Message)
	handler.NewResourceHandler(api, usecases.Resource)
	handler.NewFiscalHandler(api, usecases.Fiscal)
	handler.NewDailyBillHandler(api, usecases.DailyBill, repos.Teacher)
	handler.NewLibraryHandler(api, usecases.Library)
	handler.NewExtracurricularHandler(api, usecases.Extra)
	handler.NewReportHandler(api, infra.PDF, repos.Student, repos.Grade, repos.Tenant, repos.TerminalEvaluation, repos.AcademicPeriod, repos.Teacher, repos.Class, repos.Subject, repos.Attendance)
	handler.NewAcademicPeriodHandler(api, usecases.AcademicPeriod)
	handler.NewScholasticLevelHandler(api, usecases.Scholastic)
	handler.NewWelfareHandler(api, usecases.Welfare)
	handler.NewLogisticsHandler(api, usecases.Logistics)
	handler.NewFacilityHandler(api, usecases.Facility)
	handler.NewNotificationHandler(api, infra.Hub, repos.Message, usecases.Notification, infra.WebPush)
	handler.NewDocumentHandler(api, usecases.Document)
	handler.NewHRHandler(api, usecases.HR)
	handler.NewRolesHandler(api, repos.User)
	handler.NewTenantProfileHandler(api, a.DB, usecases.Tenant)
	handler.NewExamHandler(usecases.Exam).RegisterRoutes(api)
	handler.NewPortfolioHandler(api, usecases.Portfolio)
	handler.NewCampusOpsHandler(api, usecases.CampusOps)
	handler.NewHostelHandler(api, usecases.Hostel)
	handler.NewCommunicationHandler(api, usecases.Communication, repos.Guardian)

	// Authenticated Payment Routes
	api.POST("/payments/initialize", paymentHandler.InitializePayment)
	api.POST("/payments/initialize-wallet-topup", paymentHandler.InitializeWalletTopUp)
	api.GET("/payments/verify/:reference", paymentHandler.VerifyPayment)

	// Public Routes
	public := a.Router.Group("/api/public")
	public.GET("/payments/verify/:reference", paymentHandler.VerifyPayment)
	// 300 requests per minute per IP for public endpoints like tenant search
	publicRateLimiter := middleware.NewIPRateLimiter(300, time.Minute)
	public.Use(publicRateLimiter.Middleware())
	handler.NewPublicHandler(public, usecases.Tenant)

	// Super Admin
	superAdmin := a.Router.Group("/api/system")
	superAdmin.Use(middleware.AuthMiddleware(a.Config, repos.Blacklist))
	superAdmin.Use(middleware.RoleMiddleware(domain.RoleEcopowerAdmin))
	superAdmin.Use(middleware.AuditMiddleware(usecases.Audit))
	handler.NewTenantHandler(superAdmin, usecases.Tenant, a.DB)
	handler.NewSystemHandler(superAdmin, a.DB, a.Config)
	handler.NewAuditHandler(superAdmin, usecases.Audit)

	financeGroup := superAdmin.Group("/finance")
	handler.NewFinanceHandler(financeGroup, a.DB)

	affiliateGroup := superAdmin.Group("/affiliates")
	handler.NewAffiliateHandler(affiliateGroup, a.DB)

	handler.NewSMSHandler(api, superAdmin, a.DB, infra.Paystack)

	telemetryUseCase := usecase.NewTelemetryUseCase(a.DB)
	telemetryGroup := a.Router.Group("/api/telemetry")
	handler.NewTelemetryHandler(telemetryGroup, telemetryUseCase)
}

func (a *App) Run() {
	a.Server = &http.Server{
		Addr:    ":" + a.Config.Port,
		Handler: a.Router,
	}

	go func() {
		logger.Info("Starting server", zap.String("port", a.Config.Port))
		if err := a.Server.ListenAndServe(); err != nil && err != http.ErrServerClosed {
			logger.Fatal("Failed to run server", err)
		}
	}()

	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)
	<-quit

	logger.Info("Shutting down server...")

	ctx, cancel := context.WithTimeout(context.Background(), 15*time.Second)
	defer cancel()

	if err := a.Server.Shutdown(ctx); err != nil {
		logger.Fatal("Server forced to shutdown:", err)
	}

	logger.Info("Server exiting")
}
