package domain

import (
	"time"

	"github.com/google/uuid"
)

type InvoiceStatus string

const (
	InvoiceStatusUnpaid  InvoiceStatus = "UNPAID"
	InvoiceStatusPaid    InvoiceStatus = "PAID"
	InvoiceStatusOverdue InvoiceStatus = "OVERDUE"
)

// PlatformInvoice represents an automated invoice generated by the platform for a Tenant's SaaS subscription.
type PlatformInvoice struct {
	ID            uuid.UUID     `json:"id" gorm:"type:uuid;primaryKey;default:gen_random_uuid()"`
	TenantID      uuid.UUID     `json:"tenant_id" gorm:"type:uuid;not null;index"`
	InvoiceNumber string        `json:"invoice_number" gorm:"type:varchar(100);uniqueIndex;not null"`
	Amount        float64       `json:"amount" gorm:"not null"`
	Status        InvoiceStatus `json:"status" gorm:"type:varchar(50);not null;default:'UNPAID'"`
	PdfUrl        string        `json:"pdf_url" gorm:"type:varchar(255)"`
	DueDate       time.Time     `json:"due_date" gorm:"not null"`
	CreatedAt     time.Time     `json:"created_at" gorm:"autoCreateTime;index"`
	UpdatedAt     time.Time     `json:"updated_at" gorm:"autoUpdateTime"`
	
	Tenant        *Tenant       `json:"tenant,omitempty" gorm:"foreignKey:TenantID"`
}
